// Generated by Wrangler on Wed Jun 05 2024 22:56:09 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

export {};

declare global {
	const KV_CHATS: KVNamespace;
	const BOT_TOKEN: string;
}
